### ISSUE TITLE
什么时候把新载图和远距离打警报车会响加入配置啊？

### ISSUE THREAD

**Issue by Target5150** [fbef0102/Rotoblin-AZMod#1]
我已经迫不及待要看谁被新图和警报车坑了。

**Comment by fbef0102** [comment]
In 2019_9_7, this weekend
**1. 远距离打警报**
_sm_cvar car_alarm_distance 99999_

**2. 新载图**
[l4d_vs_stadium2_underground.cfg]
[l4d_vs_stadium3_city1.cfg]
[l4d_vs_stadium4_city2.cfg]
//delete prop_fuel_barrel (because they are different random positions between first round and second round)

[l4d_vs_hospital04_interior.cfg]
//add path for above roof tank spawn before elevator

[l4d_vs_smalltown03_ranchhouse.cfg]
//block ambulance dog hole
